
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Notification
{

    public int Id { get; set; }

    public string UserId { get; set; }

    public Nullable<System.DateTime> Time { get; set; }

    public Nullable<bool> IsRead { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
